import logging
from pathlib import Path
from typing import Callable

import numpy as np
import pytest

from pyprocar.io import vasp
from pyprocar.utils.log_utils import set_verbose_level

logger = logging.getLogger(__name__)

VERBOSE = 2
set_verbose_level(VERBOSE)

AUTO_MESH_GAMMA = """K-Spacing Value to Generate K-Mesh: 0.010
0
Gamma
  11  11   1
0.0  0.0  0.0
"""

AUTO_MESH_MP = """k-points
 0
Monkhorst Pack
 15 15 15
 0  0  0
"""


AUTO_MESH_BANDS = """KPOINTS generated by PyProcar
50 ! Grid points
Line_mode
reciprocal
0.0 0.0 0.0 ! GAMMA
0.5 -0.5 0.5 ! H

0.5 -0.5 0.5 ! H
0.0 0.0 0.5 ! N

0.0 0.0 0.5 ! N
0.0 0.0 0.0 ! GAMMA

0.0 0.0 0.0 ! GAMMA
0.25 0.25 0.25 ! P

0.25 0.25 0.25 ! P
0.5 -0.5 0.5 ! H

0.25 0.25 0.25 ! P
0.0 0.0 0.5 ! N
"""

AUTO_MESH_EXPLICIT = """Generated by PyProcar
144
Reciprocal
   -0.2000000     -0.2000000      0.0000000      1.0000000
   -0.2000000     -0.1636364      0.0000000      1.0000000
   -0.2000000     -0.1272727      0.0000000      1.0000000
"""

LINE_MODE_CARTESIAN = """PyProcar band path
20
Line_mode
Cartesian
0.0 0.0 0.0 ! GAMMA
0.5 0.5 0.0 ! X

0.5 0.5 0.0 ! X
0.5 0.5 0.5 ! R
"""


@pytest.fixture
def write_kpoints_file(tmp_path: Path) -> Callable[[str, str], Path]:
    def _writer(filename: str, contents: str) -> Path:
        filepath = tmp_path / filename
        filepath.write_text(contents)
        return filepath

    return _writer


@pytest.fixture
def kpoints_gamma_path(write_kpoints_file: Callable[[str, str], Path]) -> Path:
    return write_kpoints_file("KPOINTS_gamma", AUTO_MESH_GAMMA)


@pytest.fixture
def kpoints_monkhorst_path(write_kpoints_file: Callable[[str, str], Path]) -> Path:
    return write_kpoints_file("KPOINTS_monkhorst", AUTO_MESH_MP)


@pytest.fixture
def kpoints_line_mode_path(write_kpoints_file: Callable[[str, str], Path]) -> Path:
    return write_kpoints_file("KPOINTS_bands", AUTO_MESH_BANDS)


@pytest.fixture
def kpoints_explicit_path(write_kpoints_file: Callable[[str, str], Path]) -> Path:
    return write_kpoints_file("KPOINTS_explicit", AUTO_MESH_EXPLICIT)


@pytest.fixture
def kpoints_line_mode_cartesian_path(
    write_kpoints_file: Callable[[str, str], Path]
) -> Path:
    return write_kpoints_file("KPOINTS_line_cartesian", LINE_MODE_CARTESIAN)


class TestKpoints:
    """Test class for VASP KPOINTS file parsing."""

    def test_kpoints_from_str_gamma(self):
        """Ensure parsing from raw string mirrors file parsing."""
        kpoints = vasp.Kpoints.from_str(AUTO_MESH_GAMMA)
        assert kpoints.mode == "gamma"
        assert kpoints.kgrid == [11, 11, 1]
        assert kpoints.kshift == [0, 0, 0]
        assert kpoints.automatic is True

    def test_kpoints_auto_mesh_gamma(self, kpoints_gamma_path: Path):
        """Test parsing of automatic mesh generation with Gamma centering."""
        kpoints = vasp.Kpoints(kpoints_gamma_path)

        # Check basic properties
        assert kpoints.mode == "gamma"
        assert kpoints.automatic is True
        assert kpoints.ngrids == [0]
        assert kpoints.kgrid == [11, 11, 1]
        assert kpoints.kshift == [0, 0, 0]
        assert kpoints.cartesian is False
        assert kpoints.special_kpoints is None
        assert kpoints.knames is None
        assert "K-Spacing Value to Generate K-Mesh: 0.010" in kpoints.comment

    def test_kpoints_auto_mesh_monkhorst_pack(self, kpoints_monkhorst_path: Path):
        """Test parsing of automatic mesh generation with Monkhorst-Pack."""
        kpoints = vasp.Kpoints(kpoints_monkhorst_path)

        # Check basic properties
        assert kpoints.mode == "monkhorst-pack"
        assert kpoints.automatic is True
        assert kpoints.ngrids == [0]
        assert kpoints.kgrid == [15, 15, 15]
        assert kpoints.kshift == [0, 0, 0]
        assert kpoints.cartesian is False
        assert kpoints.special_kpoints is None
        assert kpoints.knames is None
        assert "k-points" in kpoints.comment

    def test_kpoints_explicit_mesh(self, kpoints_explicit_path: Path):
        """Test parsing of explicit k-point mesh."""
        kpoints = vasp.Kpoints(kpoints_explicit_path)

        assert kpoints.mode is None
        assert kpoints.automatic is False
        assert kpoints.ngrids == [144]
        assert kpoints.kgrid is None
        assert kpoints.kshift is None
        assert kpoints.cartesian is False
        assert kpoints.special_kpoints is None
        assert kpoints.knames is None
        assert "Generated by PyProcar" in kpoints.comment

    def test_kpoints_bands_line_mode(self, kpoints_line_mode_path: Path):
        """Test parsing of band structure k-path in line mode."""
        kpoints = vasp.Kpoints(kpoints_line_mode_path)

        assert kpoints.mode == "line"
        assert kpoints.automatic is False
        assert kpoints.ngrids == [50, 50, 50, 50, 50, 50]  # One per segment
        assert kpoints.kgrid is None
        assert kpoints.kshift is None
        assert kpoints.cartesian is False

        assert kpoints.special_kpoints is not None
        assert kpoints.knames is not None

        expected_shape = (6, 2, 3)
        assert kpoints.special_kpoints.shape == expected_shape

        np.testing.assert_allclose(
            kpoints.special_kpoints[0, 0], [0.0, 0.0, 0.0]
        )  # GAMMA
        np.testing.assert_allclose(kpoints.special_kpoints[0, 1], [0.5, -0.5, 0.5])  # H

        expected_knames_shape = (6, 2)
        assert kpoints.knames.shape == expected_knames_shape
        assert kpoints.knames[0, 0].strip() == "GAMMA"
        assert kpoints.knames[0, 1].strip() == "H"
        assert kpoints.knames[1, 0].strip() == "H"
        assert kpoints.knames[1, 1].strip() == "N"

    def test_kpoints_comment_parsing(self):
        """Test that comments are parsed correctly."""
        kpoints_gamma = vasp.Kpoints.from_str(AUTO_MESH_GAMMA)
        kpoints_mp = vasp.Kpoints.from_str(AUTO_MESH_MP)
        kpoints_explicit = vasp.Kpoints.from_str(AUTO_MESH_EXPLICIT)
        kpoints_bands = vasp.Kpoints.from_str(AUTO_MESH_BANDS)

        # Check that comments are strings and not empty
        assert isinstance(kpoints_gamma.comment, str)
        assert isinstance(kpoints_mp.comment, str)
        assert isinstance(kpoints_explicit.comment, str)
        assert isinstance(kpoints_bands.comment, str)

        assert len(kpoints_gamma.comment.strip()) > 0
        assert len(kpoints_mp.comment.strip()) > 0
        assert len(kpoints_explicit.comment.strip()) > 0
        assert len(kpoints_bands.comment.strip()) > 0

    def test_kpoints_file_not_found(self):
        """Test that appropriate error is raised when KPOINTS file doesn't exist."""
        kpoints = vasp.Kpoints("nonexistent_kpoints_file")
        with pytest.raises(FileNotFoundError):
            _ = kpoints.comment

    def test_kpoints_ngrids_single_value_expansion(
        self, kpoints_line_mode_path: Path
    ):
        """Test that single ngrids value is expanded for multiple segments in line mode."""
        kpoints = vasp.Kpoints(kpoints_line_mode_path)

        assert len(kpoints.ngrids) == 6  # 6 segments in the bands file
        assert all(val == 50 for val in kpoints.ngrids)

    def test_kpoints_automatic_detection(
        self, kpoints_gamma_path: Path, kpoints_explicit_path: Path
    ):
        """Test automatic detection based on ngrids[0] == 0."""
        kpoints_auto = vasp.Kpoints(kpoints_gamma_path)
        kpoints_explicit = vasp.Kpoints(kpoints_explicit_path)

        assert kpoints_auto.automatic is True
        assert kpoints_explicit.automatic is False

    def test_kpoints_mode_detection(
        self,
        kpoints_gamma_path: Path,
        kpoints_monkhorst_path: Path,
        kpoints_line_mode_path: Path,
    ):
        """Test detection of different k-point generation modes."""
        kpoints_gamma = vasp.Kpoints(kpoints_gamma_path)
        kpoints_mp = vasp.Kpoints(kpoints_monkhorst_path)
        kpoints_bands = vasp.Kpoints(kpoints_line_mode_path)

        assert kpoints_gamma.mode == "gamma"
        assert kpoints_mp.mode == "monkhorst-pack"
        assert kpoints_bands.mode == "line"

    def test_kpoints_cartesian_coordinate_detection(
        self, kpoints_line_mode_path: Path, kpoints_line_mode_cartesian_path: Path
    ):
        """Test detection of cartesian vs reciprocal coordinates in line mode."""
        reciprocal = vasp.Kpoints(kpoints_line_mode_path)
        cartesian = vasp.Kpoints(kpoints_line_mode_cartesian_path)

        assert reciprocal.cartesian is False
        assert cartesian.cartesian is True

    def test_kpoints_kshift_parsing(
        self, kpoints_gamma_path: Path, kpoints_monkhorst_path: Path
    ):
        """Test parsing of k-point shifts."""
        kpoints_gamma = vasp.Kpoints(kpoints_gamma_path)
        kpoints_mp = vasp.Kpoints(kpoints_monkhorst_path)

        assert kpoints_gamma.kshift == [0, 0, 0]
        assert kpoints_mp.kshift == [0, 0, 0]

    def test_kpoints_special_points_array_structure(
        self, kpoints_line_mode_path: Path
    ):
        """Test the structure of special k-points array for band calculations."""
        kpoints = vasp.Kpoints(filepath=kpoints_line_mode_path)
        assert isinstance(kpoints.special_kpoints, np.ndarray)
        assert kpoints.special_kpoints.ndim == 3
        assert kpoints.special_kpoints.shape[1] == 2
        assert kpoints.special_kpoints.shape[2] == 3
        assert kpoints.special_kpoints.dtype == np.float64

    def test_kpoints_knames_array_structure(self, kpoints_line_mode_path: Path):
        """Test the structure of k-point names array for band calculations."""
        kpoints = vasp.Kpoints(kpoints_line_mode_path)
        assert isinstance(kpoints.knames, np.ndarray)
        assert kpoints.knames.ndim == 2
        assert kpoints.knames.shape[1] == 2
        for i in range(kpoints.knames.shape[0]):
            for j in range(kpoints.knames.shape[1]):
                assert isinstance(kpoints.knames[i, j], str)
                assert len(kpoints.knames[i, j].strip()) > 0

    def test_kpoints_comment_cleanup(self, kpoints_line_mode_path: Path):
        """Test that k-point names are cleaned up properly (removing ! characters)."""
        kpoints = vasp.Kpoints(kpoints_line_mode_path)
        assert isinstance(kpoints.knames, np.ndarray)
        for i in range(kpoints.knames.shape[0]):
            for j in range(kpoints.knames.shape[1]):
                assert "!" not in kpoints.knames[i, j]

    def test_mapping_interface(self, kpoints_gamma_path: Path):
        """Test Mapping interface implementation."""
        kpoints = vasp.Kpoints(kpoints_gamma_path)

        assert kpoints["mode"] == "gamma"
        keys = list(kpoints)
        assert "mode" in keys
        assert len(kpoints) == len(keys)