"""Type stubs for VTK library."""

from _typeshed import Incomplete

class vtkLookupTable:
    """VTK lookup table for color mapping."""

    def SetNumberOfTableValues(self, n: int) -> None: ...
    def SetTableValue(
        self, i: int, r: float, g: float, b: float, a: float = ...
    ) -> None: ...
    def Build(self) -> None: ...
    def GetNumberOfTableValues(self) -> int: ...

class vtkBoxClipDataSet:
    """VTK box clip data set filter."""

    def GenerateClippedOutputOn(self) -> None: ...
    def GenerateClippedOutputOff(self) -> None: ...
    def SetBoxClip(self, *bounds: Incomplete) -> None: ...
    def Update(self) -> None: ...
    def GetOutput(self, port: int = ...) -> Incomplete: ...
    def GetClippedOutput(self) -> Incomplete: ...
    def SetInputConnection(self, input: Incomplete) -> None: ...

class vtkAlgorithm:
    """Base VTK algorithm class."""

    def GetOutputPort(self, port: int = ...) -> Incomplete: ...
    def Update(self) -> None: ...

class vtkDataSet:
    """VTK data set base class."""

    pass

class vtkPlanes:
    """VTK implicit function representing planes."""

    def GetNumberOfPlanes(self) -> int: ...
    def GetPlane(self, i: int) -> vtkPlane: ...

class vtkPlane:
    """VTK implicit plane."""

    def GetNormal(self) -> tuple[float, float, float]: ...
    def GetOrigin(self) -> tuple[float, float, float]: ...
    def SetNormal(self, x: float, y: float, z: float) -> None: ...
    def SetOrigin(self, x: float, y: float, z: float) -> None: ...

def __getattr__(name: str) -> Incomplete: ...
