[project]
name = "PyProcar"
authors = [
    {name = "Francisco Muñoz", email = "fvmunoz@gmail.com"},
    {name = "Logan Lang", email = "lllang@mix.wvu.edu"},
    {name = "Aldo Romero", email = "alromero@mail.wvu.edu"},
    {name = "Sobhit Singh", email = "smsingh@mix.wvu.edu"},
    {name = "Uthpala Herath", email = "ukh0001@mix.wvu.edu"},
    {name = "Pedram Tavadze", email = "petavazohi@mix.wvu.edu"},
    {name = "Eric Bousquet", email = "eric.bousquet@uliege.be"},
    {name = "Xu He", email = "mailhexu@gmail.com"},
    {name = "Reese Boucher"},
    {name = "Freddy Farah"}
]

description = "A Python library for electronic structure pre/post-processing."
readme = {file = "README.md", content-type = "text/markdown"}  # Ensure this matches the file used
license = "MIT"
license-files = ["LICENSE"]
keywords = ["materials", "science", "plotting", "electronic structure", "DFT"]
classifiers = [
    "Programming Language :: Python :: 3",
]

dynamic = ["version"]

requires-python = ">=3.8"
dependencies = [
    "matplotlib>=3.8",
    "numpy",
    "pandas",
    "scikit-image",
    "scikit-learn",
    "scipy",
    "sympy",
    "trimesh",
    "spglib",
    "seekpath",
    "ase",
    "PyYAML",
    "gdown",
    "dill",
    "variconfig",
    "huggingface_hub",
    "pyvista[jupyter]>0.44.0",
    "vtk"
]


[project.urls]
homepage = "https://github.com/romerogroup/pyprocar"
documentation = "https://romerogroup.github.io/pyprocar/"
Issues = "https://github.com/romerogroup/pyprocar/issues"
Changelog = "https://github.com/romerogroup/pyprocar/CHANGELOG.md"

[project.scripts]
pyprocar-download = "scripts.download:main"


[tool.setuptools.packages.find]
where = ["."]
include = ["pyprocar*", "scripts*"]
exclude = ["pyprocar.tests*"]



[build-system]
build-backend = "hatchling.build"
requires = ["hatchling", "hatch-vcs"]

[tool.hatch.version]
source = "vcs"
[tool.hatch.version.raw-options]
local_scheme = "no-local-version"
search_parent_directories = true

[tool.hatch.build.hooks.vcs]
version-file = "pyprocar/_version.py"

# Theres are tools that are used in python tests

[tool.inline-snapshot]
format-command = "pixi run -e lint ruff format --stdin-filename {filename}"

[tool.basedpyright]
ignore = [
  "**/*.ipynb",
  "**/docs_hooks.py",
  "docs/",
  "sphinx/",
  "examples/",
  ".github/",
  "**/_version.py",
  "**/tests"
]
pythonPlatform = "All"
pythonVersion = "3.13"
reportAny = false
reportExplicitAny = false
reportMissingTypeStubs = false
reportUnnecessaryIsInstance = false
reportUnusedCallResult = false
reportImplicitOverride = false
typeCheckingMode = "all"
verboseOutput = false


executionEnvironments = [
  { root = "docs", reportMissingImports = false, reportMissingModuleSource = false, reportUnknownVariableType = false, reportUnknownMemberType = false, reportUnusedCallResult = false, reportUnknownArgumentType = false },
  { root = "examples", reportMissingImports = false, reportMissingModuleSource = false, reportCallIssue = false, reportArgumentType = false, reportAttributeAccessIssue = false, reportUnknownMemberType = false, reportUnknownVariableType = false, reportUnknownParameterType = false, reportUnknownArgumentType = false, reportUnusedCallResult = false, reportMissingParameterType = false, reportUntypedFunctionDecorator = false },
  # { root = "tests", reportMissingImports = false, reportMissingModuleSource = false, reportCallIssue = false, reportArgumentType = false, reportAttributeAccessIssue = false, reportUnknownMemberType = false, reportUnknownVariableType = false, reportUnknownParameterType = false, reportUnknownArgumentType = false, reportUnusedCallResult = false, reportMissingParameterType = false, reportUntypedFunctionDecorator = false },
]