"""BXSF file extractor."""

import logging
import re
from collections.abc import Iterator, Mapping
from dataclasses import dataclass
from enum import Enum
from functools import cached_property
from pathlib import Path
from typing import Any

import numpy as np

from pyprocar.utils.units import HARTREE_TO_EV

logger = logging.getLogger(__name__)


class BxsfWriter(Enum):
    """Program that wrote a BXSF file, which fixes the unit of its reciprocal vectors.

    The format leaves that unit undefined, so each writer picks its own:

    - ``WANNIER90``: 2*pi*inv(A).T in 1/Angstrom.
    - ``ABINIT``: inv(A).T in 1/Angstrom, without the 2*pi.
    - ``QE_FS``: Quantum ESPRESSO ``fs.x`` writes ``bg``, in units of 2*pi/alat.
    - ``UNKNOWN``: no recognised signature in the file.
    """

    WANNIER90 = "Generated by the Wannier90 code"
    ABINIT = "generated by the ABINIT package"
    QE_FS = "aimed at Visualization of Fermi Surface"
    UNKNOWN = ""

    @property
    def energy_to_ev(self) -> float:
        """Factor from the writer's energy unit to eV. ABINIT ``printbxsf`` writes Hartree."""
        return HARTREE_TO_EV if self is BxsfWriter.ABINIT else 1.0


_ABINIT_SPIN_NOTE = "the first band is relative to spin-up electrons"


@dataclass(frozen=True, slots=True)
class _BandGrid:
    nkfs_dim: tuple[int, int, int]
    origin: np.ndarray
    reciprocal_lattice: np.ndarray
    values_with_boundary: np.ndarray
    band_labels: tuple[int, ...]


def _parse_band_grid(file_str: str) -> _BandGrid:
    match = re.search(r"BEGIN_BLOCK_BANDGRID_3D(.*?)END_BANDGRID_3D", file_str, re.DOTALL)
    if match is None:
        raise ValueError("No BEGIN_BLOCK_BANDGRID_3D ... END_BANDGRID_3D block in BXSF file")
    header, *labelled_texts = re.split(r"^\s*BAND:\s*(\d+)\s*$", match.group(1), flags=re.MULTILINE)
    band_labels = tuple(int(label) for label in labelled_texts[0::2])
    band_texts = labelled_texts[1::2]

    lines = [line.strip() for line in header.splitlines()]
    lines = [line for line in lines if line and not line.startswith("#")]
    if len(lines) < 6:
        raise ValueError(f"BXSF band grid header has {len(lines)} lines, expected at least 6")
    n_bands_line, dims_line, origin_line, *vector_lines = lines[-6:]
    n_bands = int(n_bands_line)
    n1, n2, n3 = (int(x) for x in dims_line.split())

    if len(band_texts) != n_bands:
        raise ValueError(
            f"BXSF header declares {n_bands} bands but has {len(band_texts)} BAND blocks"
        )
    n_points = n1 * n2 * n3
    fortran_exponent = str.maketrans("dD", "eE")
    blocks = [
        np.array(text.translate(fortran_exponent).split(), dtype=float) for text in band_texts
    ]
    for i, block in enumerate(blocks, start=1):
        if block.size != n_points:
            raise ValueError(f"BXSF BAND block {i} has {block.size} values, expected {n_points}")

    return _BandGrid(
        nkfs_dim=(n1, n2, n3),
        origin=np.array(origin_line.split(), dtype=float),
        reciprocal_lattice=np.array([line.split() for line in vector_lines], dtype=float),
        values_with_boundary=np.array(blocks).reshape(n_bands, n_points),
        band_labels=band_labels,
    )


class Bxsf(Mapping[str, Any]):
    """Extractor for BXSF (XCrySDen Band Structure Format) files.

    BXSF files contain band energies on a uniform k-grid for Fermi surface visualization.
    The format includes redundant boundary points (+1 in each dimension) which are
    excluded in the actual k-grid.

    Parameters
    ----------
    filepath : str | Path | None
        Path to .bxsf file.
    file_str : str
        Content of .bxsf file as string.
    """

    def __init__(self, filepath: str | Path | None = None, file_str: str = ""):
        logger.info(f"Initializing Bxsf extractor for {filepath}")
        self._filepath = filepath
        self._file_str = file_str

    @classmethod
    def from_str(cls, file_str: str) -> "Bxsf":
        """Create extractor from file content string."""
        return cls(file_str=file_str)

    @property
    def filepath(self) -> Path | None:
        if self._filepath is None:
            return None
        return Path(self._filepath)

    @cached_property
    def file_str(self) -> str:
        if self._file_str == "" and self.filepath is not None:
            with open(self.filepath) as f:
                self._file_str = f.read()
        elif self._file_str == "" and self.filepath is None:
            raise ValueError("No file path or file string provided")
        return self._file_str

    @cached_property
    def fermi_energy(self) -> float:
        """Fermi energy in eV."""
        match = re.findall(r"Fermi\s+Energy:\s*([\d.eE+-]+)", self.file_str)
        if not match:
            raise ValueError("No Fermi energy found in BXSF file")
        return float(match[0]) * self.writer.energy_to_ev

    @cached_property
    def writer(self) -> BxsfWriter:
        """Program that wrote the file, read from the signature in its header."""
        for writer in BxsfWriter:
            if writer.value and writer.value in self.file_str:
                return writer
        return BxsfWriter.UNKNOWN

    @cached_property
    def n_spins(self) -> int:
        """2 when ABINIT interleaves spin-up and spin-down ``BAND:`` blocks, else 1."""
        if self.writer is BxsfWriter.ABINIT and _ABINIT_SPIN_NOTE in self.file_str:
            return 2
        return 1

    @cached_property
    def _band_grid(self) -> _BandGrid:
        return _parse_band_grid(self.file_str)

    @cached_property
    def reciprocal_lattice(self) -> np.ndarray:
        """Reciprocal lattice vectors (3x3 array) as written, in the writer's units."""
        return self._band_grid.reciprocal_lattice

    @cached_property
    def origin(self) -> np.ndarray:
        """Origin of k-grid in reciprocal space."""
        return self._band_grid.origin

    @cached_property
    def nkfs_dim(self) -> np.ndarray:
        """Grid dimensions including redundant boundary points."""
        return np.array(self._band_grid.nkfs_dim)

    @cached_property
    def nk_dim(self) -> tuple[int, int, int]:
        """Grid dimensions excluding redundant boundary (actual k-grid)."""
        n1, n2, n3 = self._band_grid.nkfs_dim
        return (n1 - 1, n2 - 1, n3 - 1)

    @cached_property
    def band_labels(self) -> tuple[int, ...]:
        """The ``BAND:`` label of each block, in file order."""
        return self._band_grid.band_labels

    @cached_property
    def n_bands(self) -> int:
        """Number of bands per spin channel."""
        return self._band_grid.values_with_boundary.shape[0] // self.n_spins

    @cached_property
    def bands(self) -> np.ndarray:
        """Band energies in eV without the boundary. Shape: (n_kpoints, n_bands, n_spins).

        The file holds C-ordered values over the grid with its periodic images, so the last
        point along each axis is dropped.
        """
        blocks = self._band_grid.values_with_boundary.reshape(-1, *self._band_grid.nkfs_dim)
        on_grid = blocks[:, :-1, :-1, :-1].reshape(blocks.shape[0], -1).T
        return on_grid.reshape(-1, self.n_bands, self.n_spins) * self.writer.energy_to_ev

    @cached_property
    def kpoints(self) -> np.ndarray:
        """K-point coordinates in fractional reciprocal space. Shape: (n_kpoints, 3)."""
        axes = [np.arange(n) / n for n in self.nk_dim]
        return np.stack(np.meshgrid(*axes, indexing="ij"), axis=-1).reshape(-1, 3)

    # Mapping protocol
    def __getitem__(self, key: str) -> Any:
        return getattr(self, key)

    def __iter__(self) -> Iterator[str]:
        return iter(["fermi_energy", "reciprocal_lattice", "bands", "kpoints", "nk_dim"])

    def __len__(self) -> int:
        return 5
