"""Type stubs for mpl_toolkits.mplot3d.art3d."""

from _typeshed import Incomplete

class Poly3DCollection:
    def __init__(self, *args: Incomplete, **kwargs: Incomplete) -> None: ...
    def set_edgecolor(self, color: str) -> None: ...
    def set_facecolor(self, color: str) -> None: ...

def __getattr__(name: str) -> Incomplete: ...
