"""Type stubs for ipyvolume.pylab."""

from _typeshed import Incomplete

def figure(**kwargs: Incomplete) -> Incomplete: ...
def plot_trisurf(*args: Incomplete, **kwargs: Incomplete) -> Incomplete: ...
def show(**kwargs: Incomplete) -> None: ...

def __getattr__(name: str) -> Incomplete: ...
