"""Type stubs for matplotlib.pylab."""

from _typeshed import Incomplete

def figure(**kwargs: Incomplete) -> Incomplete: ...
def show(*args: Incomplete, **kwargs: Incomplete) -> None: ...

def __getattr__(name: str) -> Incomplete: ...
