"""Formats are copied from the writers' Fortran sources:

- Wannier90 ``plot.F90`` (``plot_fermi_surface``): list-directed header, one value per
  line in ``'(2E16.8)'``, energies in eV.
- ABINIT ``m_pptools.F90`` (``printbxsf``): list-directed header, ``'(7(es16.8))'`` values,
  eigenvalues and Fermi energy in Hartree, file named ``<root>_BXSF``. With ``nsppol=2`` the
  ``BAND:`` blocks alternate spin up and spin down.
- QE ``fs.x`` ``PP/src/fermisurface.f90`` (``xsf_fs``): ``'(6f10.4)'`` values in eV, ``BAND:``
  labels are the real band indices, file named ``<prefix>_fs.bxsf``.
"""

import logging
import math
from collections.abc import Iterator, Sequence
from pathlib import Path

import numpy as np
import pytest

from pyprocar.core.ebs import ElectronicBandStructure, ElectronicBandStructureMesh
from pyprocar.io.bxsf import BxsfParser

HARTREE_TO_EV = 27.211386245988


def _energies(offset: float, step: float) -> list[float]:
    return [offset + n * step for n in range(27)]


def _fortran_e(x: float) -> str:
    """Fortran ``E16.8``: mantissa in [0.1, 1)."""
    exponent = 0 if x == 0 else math.floor(math.log10(abs(x))) + 1
    return f"{x / 10.0**exponent:.8f}E{exponent:+03d}".rjust(16)


def _fortran_es(x: float) -> str:
    """Fortran ``ES16.8``: mantissa in [1, 10)."""
    return f"{x:.8E}".rjust(16)


def _rows(values: Sequence[str], per_line: int) -> str:
    return "".join(
        "".join(values[i : i + per_line]) + "\n" for i in range(0, len(values), per_line)
    )


def _wannier90(bands: Sequence[Sequence[float]]) -> str:
    text = (
        "  BEGIN_INFO\n"
        "       #\n"
        "       # this is a Band-XCRYSDEN-Structure-File\n"
        "       # for Fermi Surface Visualisation\n"
        "       #\n"
        "       # Generated by the Wannier90 code http://www.wannier.org\n"
        "       # On 3Oct2026 at 10:00:00\n"
        "       #\n"
        "       Fermi Energy:   5.5000000000000000     \n"
        "  END_INFO\n"
        "\n"
        "  BEGIN_BLOCK_BANDGRID_3D\n"
        " from_wannier_code\n"
        "  BEGIN_BANDGRID_3D_fermi\n"
        f"           {len(bands)}\n"
        "           3           3           3\n"
        " 0.0 0.0 0.0\n"
        "   1.5707963267948966        0.0000000000000000        0.0000000000000000     \n"
        "   0.0000000000000000        1.5707963267948966        0.0000000000000000     \n"
        "   0.0000000000000000        0.0000000000000000        1.5707963267948966     \n"
    )
    for i, band in enumerate(bands, start=1):
        text += f" BAND:            {i}\n" + _rows([_fortran_e(e) for e in band], 1)
    return text + " END_BANDGRID_3D\n  END_BLOCK_BANDGRID_3D\n"


def _abinit(bands: Sequence[Sequence[float]], nsppol: int) -> str:
    spin_note = ""
    if nsppol == 2:
        spin_note = (
            "    # NOTE: the first band is relative to spin-up electrons,\n"
            "    # the second band to spin-down and so on .. \n"
            "    #\n"
        )
    text = (
        "  BEGIN_INFO\n"
        "    #\n"
        "    # this is a Band-XCRYSDEN-Structure-File for Visualization of Fermi Surface\n"
        "    # generated by the ABINIT package\n"
        "    #\n"
        f"    #  bands between            1  and            {len(bands) // nsppol}\n"
        "    #\n"
        f"{spin_note}    # Launch as: xcrysden --bxsf \n"
        "    #\n"
        "   Fermi Energy:   2.93710000E-01\n"
        "  END_INFO\n"
        "  \n"
        "  BEGIN_BLOCK_BANDGRID_3D\n"
        "  band_energies\n"
        "  BEGIN_BANDGRID_3D\n"
        f"             {len(bands)}\n"
        "             3           3           3\n"
        "    0.0000000000000000        0.0000000000000000        0.0000000000000000     \n"
        "   0.25000000000000000        0.0000000000000000        0.0000000000000000     \n"
        "    0.0000000000000000       0.25000000000000000        0.0000000000000000     \n"
        "    0.0000000000000000        0.0000000000000000       0.25000000000000000     \n"
    )
    for i, band in enumerate(bands, start=1):
        text += f"  BAND:            {i}\n" + _rows([_fortran_es(e) for e in band], 7)
    return text + "   END_BANDGRID_3D\n  END_BLOCK_BANDGRID_3D\n"


def _qe_fs(bands: Sequence[Sequence[float]], first_band: int, grid_header: str = "") -> str:
    text = (
        " BEGIN_INFO\n"
        "   #\n"
        "   # this is a Band-XCRYSDEN-Structure-File\n"
        "   # aimed at Visualization of Fermi Surface\n"
        "   #\n"
        "   # Case:   Al_fs.bxsf\n"
        "   #\n"
        " Fermi Energy:          7.9923\n"
        " END_INFO\n"
        " BEGIN_BLOCK_BANDGRID_3D\n"
        f"{grid_header} band_energies\n"
        " BANDGRID_3D_BANDS\n"
        f"{len(bands):5d}\n"
        "    3    3    3\n"
        "  0.000000  0.000000  0.000000\n"
        " -1.000000 -1.000000  1.000000\n"
        "  1.000000  1.000000  1.000000\n"
        " -1.000000  1.000000 -1.000000\n"
    )
    for i, band in enumerate(bands, start=first_band):
        text += f"BAND:{i:4d}\n" + _rows([f"{e:10.4f}" for e in band], 6)
    return text + " END_BANDGRID_3D\n END_BLOCK_BANDGRID_3D\n"


AL_SCF_OUT = """\

     Program PWSCF v.7.2 starts on  2Oct2026 at 11:30:00

     bravais-lattice index     =            2
     lattice parameter (alat)  =       7.6500  a.u.
"""


def _bands(ebs: ElectronicBandStructure | None) -> np.ndarray:
    assert ebs is not None
    assert ebs.bands is not None
    return ebs.bands.value


@pytest.fixture
def user_warnings(
    caplog: pytest.LogCaptureFixture,
) -> Iterator[pytest.LogCaptureFixture]:
    user_logger = logging.getLogger("user")
    user_logger.addHandler(caplog.handler)
    with caplog.at_level(logging.WARNING, logger="user"):
        yield caplog
    user_logger.removeHandler(caplog.handler)


def test_wannier90_bands_load_in_ev(tmp_path: Path) -> None:
    (tmp_path / "wannier90.bxsf").write_text(
        _wannier90([_energies(-1.5, 0.25), _energies(4.0, 0.125)])
    )

    ebs = BxsfParser(tmp_path, filepaths="wannier90.bxsf").ebs
    bands = _bands(ebs)

    assert bands.shape == (8, 2, 1)
    assert ebs is not None
    assert ebs.kpoints[1] == pytest.approx([0.5, 0.0, 0.0])
    assert ebs.fermi == pytest.approx(5.5)
    assert bands[:, 0, 0] == pytest.approx([-1.5, 0.75, -0.75, 1.5, -1.25, 1.0, -0.5, 1.75])
    assert bands[:, 1, 0] == pytest.approx([4.0, 5.125, 4.375, 5.5, 4.125, 5.25, 4.5, 5.625])


def test_abinit_bands_and_fermi_energy_convert_from_hartree_to_ev(tmp_path: Path) -> None:
    (tmp_path / "outo_BXSF").write_text(_abinit([_energies(0.25, 0.001)], nsppol=1))

    ebs = BxsfParser(tmp_path, filepaths="outo_BXSF").ebs
    bands = _bands(ebs)

    assert bands.shape == (8, 1, 1)
    assert ebs is not None
    assert ebs.fermi == pytest.approx(0.29371 * HARTREE_TO_EV)
    hartree = [0.250, 0.259, 0.253, 0.262, 0.251, 0.260, 0.254, 0.263]
    assert bands[:, 0, 0] == pytest.approx([e * HARTREE_TO_EV for e in hartree])


def test_abinit_spin_polarized_blocks_alternate_up_and_down(tmp_path: Path) -> None:
    up_1, down_1 = _energies(0.20, 0.001), _energies(0.21, 0.001)
    up_2, down_2 = _energies(0.30, 0.001), _energies(0.31, 0.001)
    (tmp_path / "outo_BXSF").write_text(_abinit([up_1, down_1, up_2, down_2], nsppol=2))

    bands = _bands(BxsfParser(tmp_path, filepaths="outo_BXSF").ebs)

    assert bands.shape == (8, 2, 2)
    assert bands[0] == pytest.approx(np.array([[0.20, 0.21], [0.30, 0.31]]) * HARTREE_TO_EV)
    assert bands[7, :, 1] == pytest.approx(np.array([0.223, 0.323]) * HARTREE_TO_EV)


def test_from_code_finds_qe_fs_file_and_keeps_only_the_written_bands(tmp_path: Path) -> None:
    (tmp_path / "Al_fs.bxsf").write_text(
        _qe_fs([_energies(3.0, 0.5), _energies(8.0, 0.5)], first_band=2)
    )
    (tmp_path / "scf.out").write_text(AL_SCF_OUT)

    ebs = ElectronicBandStructureMesh.from_code("bxsf", str(tmp_path))
    bands = _bands(ebs)

    assert bands.shape == (8, 2, 1)
    assert bands[:, 0, 0] == pytest.approx([3.0, 7.5, 4.5, 9.0, 3.5, 8.0, 5.0, 9.5])
    assert bands[:, 1, 0] == pytest.approx([8.0, 12.5, 9.5, 14.0, 8.5, 13.0, 10.0, 14.5])
    lattice = ebs.reciprocal_lattice
    assert lattice is not None
    assert lattice[1] == pytest.approx([0.2470, 0.2470, 0.2470], abs=1e-4)


def test_from_code_finds_abinit_bxsf_file(tmp_path: Path) -> None:
    (tmp_path / "outo_BXSF").write_text(_abinit([_energies(0.25, 0.001)], nsppol=1))

    bands = _bands(ElectronicBandStructureMesh.from_code("bxsf", str(tmp_path)))

    assert bands[0, 0, 0] == pytest.approx(0.25 * HARTREE_TO_EV)


def test_qe_alat_is_not_taken_from_a_calculation_in_a_subdirectory(
    tmp_path: Path, user_warnings: pytest.LogCaptureFixture
) -> None:
    (tmp_path / "Al_fs.bxsf").write_text(_qe_fs([_energies(3.0, 0.5)], first_band=2))
    (tmp_path / "other").mkdir()
    (tmp_path / "other" / "scf.out").write_text(AL_SCF_OUT.replace("7.6500", "10.0000"))

    lattice = BxsfParser(tmp_path, filepaths="Al_fs.bxsf").reciprocal_lattice

    assert lattice is not None
    assert lattice[1] == pytest.approx([1.0, 1.0, 1.0])
    assert "alat was found" in user_warnings.text


def test_band_grid_header_tolerates_blank_and_comment_lines(tmp_path: Path) -> None:
    text = _qe_fs([_energies(3.0, 0.5)], first_band=1, grid_header="\n   # grid follows\n\n")
    (tmp_path / "in.bxsf").write_text(text)

    bands = _bands(BxsfParser(tmp_path).ebs)

    assert bands[:, 0, 0] == pytest.approx([3.0, 7.5, 4.5, 9.0, 3.5, 8.0, 5.0, 9.5])


def test_from_code_reads_the_qe_fs_spin_pair_as_two_spins(tmp_path: Path) -> None:
    (tmp_path / "Al_fsup.bxsf").write_text(_qe_fs([_energies(3.0, 0.5)], first_band=2))
    (tmp_path / "Al_fsdw.bxsf").write_text(_qe_fs([_energies(4.0, 0.5)], first_band=2))
    (tmp_path / "scf.out").write_text(AL_SCF_OUT)

    bands = _bands(ElectronicBandStructureMesh.from_code("bxsf", str(tmp_path)))

    assert bands.shape == (8, 1, 2)
    assert bands[:, 0, 0] == pytest.approx([3.0, 7.5, 4.5, 9.0, 3.5, 8.0, 5.0, 9.5])
    assert bands[:, 0, 1] == pytest.approx([4.0, 8.5, 5.5, 10.0, 4.5, 9.0, 6.0, 10.5])


def test_qe_fs_spin_pair_with_different_bands_is_refused(
    tmp_path: Path, user_warnings: pytest.LogCaptureFixture
) -> None:
    (tmp_path / "Al_fsup.bxsf").write_text(_qe_fs([_energies(3.0, 0.5)], first_band=2))
    (tmp_path / "Al_fsdw.bxsf").write_text(_qe_fs([_energies(4.0, 0.5)], first_band=3))

    ebs = BxsfParser(tmp_path).ebs

    assert ebs is None
    assert "spin-up file holds bands [2]" in user_warnings.text
    assert "spin-down file holds bands [3]" in user_warnings.text


def test_several_bxsf_files_read_the_first_by_name_and_warn(
    tmp_path: Path, user_warnings: pytest.LogCaptureFixture
) -> None:
    (tmp_path / "b.bxsf").write_text(_qe_fs([_energies(8.0, 0.5)], first_band=1))
    (tmp_path / "a.bxsf").write_text(_qe_fs([_energies(3.0, 0.5)], first_band=1))

    bands = _bands(BxsfParser(tmp_path).ebs)

    assert bands[0, 0, 0] == pytest.approx(3.0)
    assert "Found several BXSF files" in user_warnings.text
    assert "reading a.bxsf" in user_warnings.text


def test_band_values_accept_fortran_d_exponents(tmp_path: Path) -> None:
    text = _wannier90([_energies(-1.5, 0.25)]).replace("E+", "D+").replace("E-", "D-")
    (tmp_path / "wannier90.bxsf").write_text(text)

    bands = _bands(BxsfParser(tmp_path, filepaths="wannier90.bxsf").ebs)

    assert bands[:, 0, 0] == pytest.approx([-1.5, 0.75, -0.75, 1.5, -1.25, 1.0, -0.5, 1.75])
