"""Tests for BXSF parser."""

import logging
from collections.abc import Iterator
from pathlib import Path

import numpy as np
import pytest

from pyprocar.core.ebs import ElectronicBandStructureMesh
from pyprocar.core.kpoints import KGRID_MODE
from pyprocar.io.bxsf import BxsfParser

BXSF_STR = """\
BEGIN_INFO
  Fermi Energy: 5.5000
END_INFO

BEGIN_BLOCK_BANDGRID_3D
  fermi_surface
  BEGIN_BANDGRID_3D_fermi
    1
    3 3 3
    0.0 0.0 0.0
    1.0 0.0 0.0
    0.0 1.0 0.0
    0.0 0.0 1.0
    BAND: 1
    1.0 2.0 3.0
    4.0 5.0 6.0
    7.0 8.0 9.0

    1.0 2.0 3.0
    4.0 5.0 6.0
    7.0 8.0 9.0

    1.0 2.0 3.0
    4.0 5.0 6.0
    7.0 8.0 9.0
  END_BANDGRID_3D_fermi
END_BLOCK_BANDGRID_3D
"""


@pytest.fixture
def bxsf_dir(tmp_path: Path) -> Path:
    """Create temporary directory with BXSF file."""
    filepath = tmp_path / "in.bxsf"
    filepath.write_text(BXSF_STR)
    return tmp_path


class TestBxsfParser:
    """Tests for BxsfParser class."""

    def test_parser_creates_ebs(self, bxsf_dir: Path) -> None:
        """Test parser creates ElectronicBandStructureMesh."""
        parser = BxsfParser(bxsf_dir)
        ebs = parser.ebs
        assert ebs is not None
        assert isinstance(ebs, ElectronicBandStructureMesh)

    def test_parser_kgrid_info(self, bxsf_dir: Path) -> None:
        """Test parser provides kgrid_info."""
        parser = BxsfParser(bxsf_dir)
        assert parser.kgrid_info is not None
        assert parser.kgrid_info.kgrid == (2, 2, 2)
        assert parser.kgrid_info.kgrid_mode == KGRID_MODE.GAMMA

    def test_parser_fermi_energy(self, bxsf_dir: Path) -> None:
        """Test EBS has correct Fermi energy."""
        parser = BxsfParser(bxsf_dir)
        ebs = parser.ebs
        assert ebs is not None
        assert ebs.fermi == pytest.approx(5.5)

    def test_parser_returns_none_properties(self, bxsf_dir: Path) -> None:
        """Test parser returns None for unsupported properties."""
        parser = BxsfParser(bxsf_dir)
        assert parser.kpath is None
        assert parser.structure is None
        assert parser.dos is None


class TestBxsfParserMissingFiles:
    """Tests for BxsfParser with missing files."""

    def test_missing_file_returns_none_ebs(self, tmp_path: Path) -> None:
        """Test parser handles missing file gracefully."""
        parser = BxsfParser(tmp_path, filepaths="nonexistent.bxsf")
        assert parser.ebs is None

    def test_missing_file_returns_none_kgrid_info(self, tmp_path: Path) -> None:
        """Test parser returns None kgrid_info for missing file."""
        parser = BxsfParser(tmp_path, filepaths="nonexistent.bxsf")
        assert parser.kgrid_info is None


class TestBxsfParserFromStr:
    """Tests for BxsfParser.from_str()."""

    def test_from_str_creates_ebs(self) -> None:
        """Test from_str creates working parser."""
        parser = BxsfParser.from_str(BXSF_STR)
        ebs = parser.ebs
        assert ebs is not None
        assert isinstance(ebs, ElectronicBandStructureMesh)

    def test_from_str_multiple_files(self) -> None:
        """Test from_str with multiple file strings."""
        parser = BxsfParser.from_str(BXSF_STR)
        assert len(parser._extractors) == 1


class TestBxsfParserCustomFilepath:
    """Tests for BxsfParser with custom filepaths."""

    def test_custom_filepath(self, tmp_path: Path) -> None:
        """Test parser with custom filepath."""
        filepath = tmp_path / "custom.bxsf"
        filepath.write_text(BXSF_STR)

        parser = BxsfParser(tmp_path, filepaths="custom.bxsf")
        assert parser.ebs is not None


GRID_BLOCK = """\
    1
    2 2 2
    0.0 0.0 0.0
{vectors}
    BAND: 1
    1.0 2.0 3.0 4.0 5.0 6.0 7.0 8.0
"""

QE_FS_HEADER = """\
 BEGIN_INFO
   #
   # this is a Band-XCRYSDEN-Structure-File
   # aimed at Visualization of Fermi Surface
   #
   # Case:   Al_fs.bxsf
   #
 Fermi Energy:          7.9923
 END_INFO
 BEGIN_BLOCK_BANDGRID_3D
 band_energies
 BANDGRID_3D_BANDS
"""

ABINIT_HEADER = """\
  BEGIN_INFO
    #
    # this is a Band-XCRYSDEN-Structure-File for Visualization of Fermi Surface
    # generated by the ABINIT package
    #
    #  bands between 1 and 1
    #
    # Launch as: xcrysden --bxsf
    #
   Fermi Energy:   2.93710000E-01
  END_INFO

  BEGIN_BLOCK_BANDGRID_3D
  band_energies
  BEGIN_BANDGRID_3D
"""

FOOTER = " END_BANDGRID_3D\n END_BLOCK_BANDGRID_3D\n"

AL_FS_VECTORS = (
    " -1.000000 -1.000000  1.000000\n  1.000000  1.000000  1.000000\n -1.000000  1.000000 -1.000000"
)
AL_SCF_OUT = """\

     Program PWSCF v.7.2 starts on  2Oct2026 at 11:30:00

     bravais-lattice index     =            2
     lattice parameter (alat)  =       7.6500  a.u.
"""


@pytest.fixture
def user_warnings(
    caplog: pytest.LogCaptureFixture,
) -> Iterator[pytest.LogCaptureFixture]:
    """Capture warnings on the non-propagating "user" logger."""
    user_logger = logging.getLogger("user")
    user_logger.addHandler(caplog.handler)
    with caplog.at_level(logging.WARNING, logger="user"):
        yield caplog
    user_logger.removeHandler(caplog.handler)


def _bxsf(header: str, vectors: str) -> str:
    return header + GRID_BLOCK.format(vectors=vectors) + FOOTER


def test_qe_fs_bxsf_scales_b_by_the_alat_of_the_calculation_beside_it(
    tmp_path: Path,
) -> None:
    """fs.x writes bg in units of 2*pi/alat; fcc Al with alat = 7.65 bohr has inv(A).T = 0.2470."""
    (tmp_path / "in.bxsf").write_text(_bxsf(QE_FS_HEADER, AL_FS_VECTORS))
    (tmp_path / "scf.out").write_text(AL_SCF_OUT)

    lattice = BxsfParser(tmp_path).reciprocal_lattice

    assert lattice is not None
    expected = 0.2470 * np.array([[-1, -1, 1], [1, 1, 1], [-1, 1, -1]])
    assert np.allclose(lattice, expected, atol=1e-4)


def test_qe_fs_bxsf_without_alat_keeps_b_in_units_of_one_over_alat(
    user_warnings: pytest.LogCaptureFixture,
) -> None:
    """With no QE output to supply alat, b stays as written and the user is warned."""
    lattice = BxsfParser.from_str(_bxsf(QE_FS_HEADER, AL_FS_VECTORS)).reciprocal_lattice

    assert lattice is not None
    assert np.allclose(lattice, [[-1, -1, 1], [1, 1, 1], [-1, 1, -1]])
    assert "alat was found" in user_warnings.text


def test_abinit_bxsf_keeps_b_as_written() -> None:
    """ABINIT writes gprimd / Bohr_Ang, which is already 1/Angstrom without the 2*pi."""
    vectors = "    0.25 0.0 0.0\n    0.0 0.25 0.0\n    0.0 0.0 0.25"

    lattice = BxsfParser.from_str(_bxsf(ABINIT_HEADER, vectors)).reciprocal_lattice

    assert lattice is not None
    assert np.allclose(lattice, np.eye(3) * 0.25)


def test_wannier90_bxsf_drops_the_two_pi() -> None:
    """Wannier90 writes recip_lattice = 2*pi*inv(A).T in 1/Angstrom; here a = 4 Angstrom."""
    header = (
        " BEGIN_INFO\n"
        "       #\n"
        "       # this is a Band-XCRYSDEN-Structure-File\n"
        "       # for Fermi Surface Visualisation\n"
        "       #\n"
        "       # Generated by the Wannier90 code http://www.wannier.org\n"
        "       #\n"
        "  Fermi Energy:    5.5\n"
        " END_INFO\n"
        "\n"
        "  BEGIN_BLOCK_BANDGRID_3D\n"
        " from_wannier_code\n"
        "  BEGIN_BANDGRID_3D_fermi\n"
    )
    b = 2 * np.pi / 4
    vectors = f"    {b} 0.0 0.0\n    0.0 {b} 0.0\n    0.0 0.0 {b}"

    lattice = BxsfParser.from_str(_bxsf(header, vectors)).reciprocal_lattice

    assert lattice is not None
    assert np.allclose(lattice, np.eye(3) * 0.25)


def test_unknown_writer_assumes_the_two_pi_and_warns(
    user_warnings: pytest.LogCaptureFixture,
) -> None:
    """A file with no writer signature is read in the XCrySDen/Wannier90 convention."""
    b = 2 * np.pi / 4
    vectors = f"    {b} 0.0 0.0\n    0.0 {b} 0.0\n    0.0 0.0 {b}\n"
    unknown_bxsf = BXSF_STR.replace("    1.0 0.0 0.0\n    0.0 1.0 0.0\n    0.0 0.0 1.0\n", vectors)
    lattice = BxsfParser.from_str(unknown_bxsf).reciprocal_lattice

    assert lattice is not None
    assert np.allclose(lattice, np.eye(3) * 0.25)
    assert "writer not recognised" in user_warnings.text
